'model_name' : 'vswin-tiny-patch4-window4-224_scratch'
'epochs_total': 25
'epochs_froozen': 0
'n_inst': 2000
'train_sz': 0.75
'seq_len': 8
'batch_size': 5
'base_lr' : 0.00008
'drop_rate' : 0.3
'attn_drop_rate' : 0.2
'drop_path_rate' : 0.1
'patch_size' : [2,4,4]
'window_size' : [4,4,4]
'tags' : {
    'Model': 'vswin-tiny-patch4-window4-224_scratch',
    'Type': 'Train',
    'Seeds': [0]
}
'eval_dir' : "Evaluation"
'seed' : 0
'pretrained' : 'skip'
'PVs': 0
'min_val_loss' : 0.3
'min_delta_loss': 0.009
'patience': 5