'model_name' : 'vivit-tiny-patch16-224_scratch'
'epochs_total': 3
'epochs_froozen': 1
'n_inst': 
'train_sz': 0.75
'seq_len': 4
'batch_size': 21
'base_lr' : 0.00008
'drop_rate' : 0.3
'attn_drop_rate' : 0.2
'drop_path_rate' : 0.1
'patch_size' : [2,16,16]
'window_size' : [2,4,4]
'tags' : {
    'Model': 'vivit-tiny-patch16-224_scratch',
    'Type': 'SelfSupervisedTraining',
    'Seeds': [0]
}
'eval_dir' : "Evaluation"
'seed' : 0
'pretrained' : 'skip'
'PVs': 2
'min_val_loss' : 0.3
'min_delta_loss': 0.009
'patience': 5
'pretrained_dir':
'num_classes' : 3
'final_actv' : None
'loss' : cross # {cross, huber}
'transfer_learning' : False
'pv_learning' : False
'fine_tune' : False