'model_name' : 'swin-tiny-patch4-window7-224_scratch'
'epochs_total': 2
'epochs_froozen': 0
'n_inst': 100
'train_sz': 0.7
'seq_len': 0
'batch_size': 2
'base_lr' : 0.0001
'drop_rate' : 0.3
'attn_drop_rate' : 0.2
'drop_path_rate' : 0.1
'tags' : {
    'Model': 'swin-tiny-patch4-window7-224_scratch',
    'Type': 'Debug',
    'Seeds': [0]
}
'eval_dir' : "Evaluation"
'seed' : 0
'pretrained' : 'skip'
'PVs': 0