'model_name' : 'swin-tiny-patch4-window7-224_scratch'
'epochs_total': 25
'epochs_froozen': 0
'n_inst': 100
'train_sz': 0.5
'seq_len': 0
'batch_size': 21
'base_lr' : 0.0001
'drop_rate' : 0.3
'attn_drop_rate' : 0.2
'drop_path_rate' : 0.1
'tags' : {
    'Model': 'swin-tiny-patch4-window7-224_scratch',
    'Type': 'Training',
    'Seeds': [0]
}
'eval_dir' : "Evaluation"
'seed' : 0
'pretrained' : 'skip'
'PVs': 0
'min_val_loss' : 0.9
'min_delta_loss': 0.009
'patience': 3