0:
  params:
  - classifier.bias
  - classifier.weight 
  lr: 5e-4
  max_transition_epochs: 1
1:
  params:
  - classifier.bias
  - classifier.weight
    lr: 8e-5
  max_transition_epochs: 1
2:
  params:
  - classifier.*
  - feature_extractor.norm.bias
  - feature_extractor.norm.weight
  max_transition_epochs: 2
3:
  params:
  - classifier.*
  - feature_extractor.norm.bias
  - feature_extractor.norm.weight
  - feature_extractor.blocks.11.mlp.fc2.bias
  - feature_extractor.blocks.11.mlp.fc2.weight
  - feature_extractor.blocks.11.mlp.fc1.bias
  - feature_extractor.blocks.11.mlp.fc1.weight
4:
  params:
  - classifier.*
  - feature_extractor.norm.bias
  - feature_extractor.norm.weight
  - feature_extractor.blocks.11.mlp.fc2.bias
  - feature_extractor.blocks.11.mlp.fc2.weight
  - feature_extractor.blocks.11.mlp.fc1.bias
  - feature_extractor.blocks.11.mlp.fc1.weight
5:
  params:
  - feature_extractor.blocks.11.norm2.bias
  - feature_extractor.blocks.11.norm2.weight
6:
  params:
  - feature_extractor.blocks.11.attn.proj.bias
  - feature_extractor.blocks.11.attn.proj.weight
7:
  params:
  - feature_extractor.blocks.11.attn.qkv.bias
  - feature_extractor.blocks.11.attn.qkv.weight
8:
  params:
  - feature_extractor.blocks.11.norm1.bias
  - feature_extractor.blocks.11.norm1.weight
9:
  params:
  - feature_extractor.blocks.10.mlp.fc2.bias
  - feature_extractor.blocks.10.mlp.fc2.weight
10:
  params:
  - feature_extractor.blocks.10.mlp.fc1.bias
  - feature_extractor.blocks.10.mlp.fc1.weight
11:
  params:
  - feature_extractor.blocks.10.norm2.bias
  - feature_extractor.blocks.10.norm2.weight
12:
  params:
  - feature_extractor.blocks.10.attn.proj.bias
  - feature_extractor.blocks.10.attn.proj.weight
13:
  params:
  - feature_extractor.blocks.10.attn.qkv.bias
  - feature_extractor.blocks.10.attn.qkv.weight
14:
  params:
  - feature_extractor.blocks.10.norm1.bias
  - feature_extractor.blocks.10.norm1.weight
15:
  params:
  - feature_extractor.blocks.9.mlp.fc2.bias
  - feature_extractor.blocks.9.mlp.fc2.weight
16:
  params:
  - feature_extractor.blocks.9.mlp.fc1.bias
  - feature_extractor.blocks.9.mlp.fc1.weight
17:
  params:
  - feature_extractor.blocks.9.norm2.bias
  - feature_extractor.blocks.9.norm2.weight
18:
  params:
  - feature_extractor.blocks.9.attn.proj.bias
  - feature_extractor.blocks.9.attn.proj.weight
19:
  params:
  - feature_extractor.blocks.9.attn.qkv.bias
  - feature_extractor.blocks.9.attn.qkv.weight
20:
  params:
  - feature_extractor.blocks.9.norm1.bias
  - feature_extractor.blocks.9.norm1.weight
21:
  params:
  - feature_extractor.blocks.8.mlp.fc2.bias
  - feature_extractor.blocks.8.mlp.fc2.weight
22:
  params:
  - feature_extractor.blocks.8.mlp.fc1.bias
  - feature_extractor.blocks.8.mlp.fc1.weight
23:
  params:
  - feature_extractor.blocks.8.norm2.bias
  - feature_extractor.blocks.8.norm2.weight
24:
  params:
  - feature_extractor.blocks.8.attn.proj.bias
  - feature_extractor.blocks.8.attn.proj.weight
25:
  params:
  - feature_extractor.blocks.8.attn.qkv.bias
  - feature_extractor.blocks.8.attn.qkv.weight
26:
  params:
  - feature_extractor.blocks.8.norm1.bias
  - feature_extractor.blocks.8.norm1.weight
27:
  params:
  - feature_extractor.blocks.7.mlp.fc2.bias
  - feature_extractor.blocks.7.mlp.fc2.weight
28:
  params:
  - feature_extractor.blocks.7.mlp.fc1.bias
  - feature_extractor.blocks.7.mlp.fc1.weight
29:
  params:
  - feature_extractor.blocks.7.norm2.bias
  - feature_extractor.blocks.7.norm2.weight
30:
  params:
  - feature_extractor.blocks.7.attn.proj.bias
  - feature_extractor.blocks.7.attn.proj.weight
31:
  params:
  - feature_extractor.blocks.7.attn.qkv.bias
  - feature_extractor.blocks.7.attn.qkv.weight
32:
  params:
  - feature_extractor.blocks.7.norm1.bias
  - feature_extractor.blocks.7.norm1.weight
33:
  params:
  - feature_extractor.blocks.6.mlp.fc2.bias
  - feature_extractor.blocks.6.mlp.fc2.weight
34:
  params:
  - feature_extractor.blocks.6.mlp.fc1.bias
  - feature_extractor.blocks.6.mlp.fc1.weight
35:
  params:
  - feature_extractor.blocks.6.norm2.bias
  - feature_extractor.blocks.6.norm2.weight
36:
  params:
  - feature_extractor.blocks.6.attn.proj.bias
  - feature_extractor.blocks.6.attn.proj.weight
37:
  params:
  - feature_extractor.blocks.6.attn.qkv.bias
  - feature_extractor.blocks.6.attn.qkv.weight
38:
  params:
  - feature_extractor.blocks.6.norm1.bias
  - feature_extractor.blocks.6.norm1.weight
39:
  params:
  - feature_extractor.blocks.5.mlp.fc2.bias
  - feature_extractor.blocks.5.mlp.fc2.weight
40:
  params:
  - feature_extractor.blocks.5.mlp.fc1.bias
  - feature_extractor.blocks.5.mlp.fc1.weight
41:
  params:
  - feature_extractor.blocks.5.norm2.bias
  - feature_extractor.blocks.5.norm2.weight
42:
  params:
  - feature_extractor.blocks.5.attn.proj.bias
  - feature_extractor.blocks.5.attn.proj.weight
43:
  params:
  - feature_extractor.blocks.5.attn.qkv.bias
  - feature_extractor.blocks.5.attn.qkv.weight
44:
  params:
  - feature_extractor.blocks.5.norm1.bias
  - feature_extractor.blocks.5.norm1.weight
45:
  params:
  - feature_extractor.blocks.4.mlp.fc2.bias
  - feature_extractor.blocks.4.mlp.fc2.weight
46:
  params:
  - feature_extractor.blocks.4.mlp.fc1.bias
  - feature_extractor.blocks.4.mlp.fc1.weight
47:
  params:
  - feature_extractor.blocks.4.norm2.bias
  - feature_extractor.blocks.4.norm2.weight
48:
  params:
  - feature_extractor.blocks.4.attn.proj.bias
  - feature_extractor.blocks.4.attn.proj.weight
49:
  params:
  - feature_extractor.blocks.4.attn.qkv.bias
  - feature_extractor.blocks.4.attn.qkv.weight
50:
  params:
  - feature_extractor.blocks.4.norm1.bias
  - feature_extractor.blocks.4.norm1.weight
51:
  params:
  - feature_extractor.blocks.3.mlp.fc2.bias
  - feature_extractor.blocks.3.mlp.fc2.weight
52:
  params:
  - feature_extractor.blocks.3.mlp.fc1.bias
  - feature_extractor.blocks.3.mlp.fc1.weight
53:
  params:
  - feature_extractor.blocks.3.norm2.bias
  - feature_extractor.blocks.3.norm2.weight
54:
  params:
  - feature_extractor.blocks.3.attn.proj.bias
  - feature_extractor.blocks.3.attn.proj.weight
55:
  params:
  - feature_extractor.blocks.3.attn.qkv.bias
  - feature_extractor.blocks.3.attn.qkv.weight
56:
  params:
  - feature_extractor.blocks.3.norm1.bias
  - feature_extractor.blocks.3.norm1.weight
57:
  params:
  - feature_extractor.blocks.2.mlp.fc2.bias
  - feature_extractor.blocks.2.mlp.fc2.weight
58:
  params:
  - feature_extractor.blocks.2.mlp.fc1.bias
  - feature_extractor.blocks.2.mlp.fc1.weight
59:
  params:
  - feature_extractor.blocks.2.norm2.bias
  - feature_extractor.blocks.2.norm2.weight
60:
  params:
  - feature_extractor.blocks.2.attn.proj.bias
  - feature_extractor.blocks.2.attn.proj.weight
61:
  params:
  - feature_extractor.blocks.2.attn.qkv.bias
  - feature_extractor.blocks.2.attn.qkv.weight
62:
  params:
  - feature_extractor.blocks.2.norm1.bias
  - feature_extractor.blocks.2.norm1.weight
63:
  params:
  - feature_extractor.blocks.1.mlp.fc2.bias
  - feature_extractor.blocks.1.mlp.fc2.weight
64:
  params:
  - feature_extractor.blocks.1.mlp.fc1.bias
  - feature_extractor.blocks.1.mlp.fc1.weight
65:
  params:
  - feature_extractor.blocks.1.norm2.bias
  - feature_extractor.blocks.1.norm2.weight
66:
  params:
  - feature_extractor.blocks.1.attn.proj.bias
  - feature_extractor.blocks.1.attn.proj.weight
67:
  params:
  - feature_extractor.blocks.1.attn.qkv.bias
  - feature_extractor.blocks.1.attn.qkv.weight
68:
  params:
  - feature_extractor.blocks.1.norm1.bias
  - feature_extractor.blocks.1.norm1.weight
69:
  params:
  - feature_extractor.blocks.0.mlp.fc2.bias
  - feature_extractor.blocks.0.mlp.fc2.weight
70:
  params:
  - feature_extractor.blocks.0.mlp.fc1.bias
  - feature_extractor.blocks.0.mlp.fc1.weight
71:
  params:
  - feature_extractor.blocks.0.norm2.bias
  - feature_extractor.blocks.0.norm2.weight
72:
  params:
  - feature_extractor.blocks.0.attn.proj.bias
  - feature_extractor.blocks.0.attn.proj.weight
73:
  params:
  - feature_extractor.blocks.0.attn.qkv.bias
  - feature_extractor.blocks.0.attn.qkv.weight
74:
  params:
  - feature_extractor.blocks.0.norm1.bias
  - feature_extractor.blocks.0.norm1.weight
75:
  params:
  - feature_extractor.patch_embed.proj.bias
  - feature_extractor.patch_embed.proj.weight
76:
  params:
  - feature_extractor.pos_embed
  - feature_extractor.cls_token
